name: test-j
on:
  workflow_call:
    inputs:
      flag:
        type: boolean
        default: false
      count:
        type: number
        default: 10
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-j passed"
