name: test-docs
on:
  workflow_dispatch:
jobs:
  test:
    uses: YiAgent/OpenCI/.github/workflows/reusable-docs.yml@a3231202c05a0d1dd9d6e867ae660004f8451c59
    with:
      docs-path: docs
      enable-agent: false
      deploy-docs: false
    secrets:
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      api-base-url: ${{ secrets.ANTHROPIC_BASE_URL }}
