name: test-perms
on:
  workflow_dispatch:
jobs:
  no-perm-key:
    uses: YiAgent/OpenCI/.github/workflows/_test-no-perm-key.yml@94dc602cc7f9a30d8805033a500124c2378f1538
  with-empty-perm:
    uses: YiAgent/OpenCI/.github/workflows/_test-with-empty-perm.yml@94dc602cc7f9a30d8805033a500124c2378f1538
