name: test-caller

on:
  workflow_dispatch:

jobs:
  call-internal:
    uses: ./.github/workflows/_test-reusable.yml
    with:
      message: "internal works"

  call-openci-docs:
    uses: YiAgent/OpenCI/.github/workflows/reusable-docs.yml@4e1ecadc2505761f104f3fd8d255eee4eb369d90
    with:
      docs-path: docs
      site-dir: site
    secrets:
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      api-base-url: ${{ secrets.ANTHROPIC_BASE_URL }}
