name: test-caller

on:
  workflow_dispatch:

jobs:
  call-internal:
    uses: ./.github/workflows/_test-reusable.yml
    with:
      message: "internal works"

  call-v3-explicit:
    uses: YiAgent/OpenCI/.github/workflows/deps.yml@refs/tags/v3
    with:
      runner: ubuntu-latest
