name: test-inputs
on:
  workflow_dispatch:
jobs:
  g:
    uses: ./.github/workflows/_test-g.yml
  h:
    uses: ./.github/workflows/_test-h.yml
  i:
    uses: ./.github/workflows/_test-i.yml
  j:
    uses: ./.github/workflows/_test-j.yml
