name: test-reusable

on:
  workflow_dispatch:

jobs:
  call-deps:
    uses: YiAgent/OpenCI/.github/workflows/reusable-deps.yml@8abd56ca266671e47760ae259a91d3eb6fc63ade
    with:
      runner: ubuntu-latest
