name: test-cross

on:
  workflow_dispatch:

jobs:
  call-openci:
    uses: YiAgent/OpenCI/.github/workflows/reusable-deps.yml@f9c2c23543336c47b39addd8386e5bafcebf7e2a
    with:
      runner: ubuntu-latest
